### ISSUE TITLE
exclude the first column of csv 

### ISSUE THREAD

**Issue by megharana** [megharana/mmt-challange#8]
As the first column named as "id" is being used as an identifier for all rows. It is being counted as data. 

So effort must be made to remove it before building dataframe out of train.csv file, and then move ahead with other proceedings using that dataset.

**Comment by acabhishek942** [comment]
please provide screenshot

**Comment by megharana** [comment]
![image](https://user-images.githubusercontent.com/26412037/40736000-58c08b58-645a-11e8-9dc0-11a8352198fb.png)

**Comment by acabhishek942** [comment]
Invalid issue
